version: '3.7'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=superhero-db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/pgdata
      - ./scripts/init.sh:/docker-entrypoint-initdb.d/init.sh
    restart: unless-stopped

  api:
    build: ./app
    image: api
    container_name: flask-api
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    restart: unless-stopped

  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx
    ports:
      - '80:80'
    links:
      - api
    depends_on:
      - api
    restart: unless-stopped