version: '3.7'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=superhero-db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/pgdata
      - ./scripts/init.sh:/docker-entrypoint-initdb.d/init.sh
    restart: unless-stopped

  api:
    build: ./app
    image: api:latest
    container_name: flask-api
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    image: custom-nginx:latest
    container_name: nginx
    ports:
      - '80:80'
    links:
      - api
    depends_on:
      - api
    restart: unless-stopped

#  prometheus:
#    image: prom/prometheus:latest
#    container_name: prometheus
#    ports:
#      - '9090:9090'
#    volumes:
#      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#    command:
#      - --config.file=/etc/prometheus/prometheus.yml
#    depends_on:
#      - api
#      - postgres
#      - nginx