apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginxser.serviceName }}
spec:
  selector:
    app: {{ .Values.nginxser.appLabel }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.nginxser.servicePort }}
    targetPort: {{ .Values.nginxser.targetPort }}
  type: {{ .Values.nginxser.serviceType }}