name: Deploy App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and push to Docker Hub
      run: |
        docker-compose build
        echo "Checking"
        echo $secrets.DOCKER_PASSWORD
        echo $secrets.DOCKER_USERNAME
#        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
#        docker-compose push
    - name: Run app
      run: |
        docker-compose up -d
    - name: Test app
      run: |
        sleep 10
        sh scripts/test_app.sh
    - name: Turn down
      run: |
        docker-compose down
