name: Deploy App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push to Docker Hub
      run: |
        docker-compose --build
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker-compose push
    - name: Run app
      run: |
        docker-compose up
    - name: Test app
      run: |
        sleep 10
        curl http://localhost:5000/users/all/
        curl http://localhost/user-management/
    - name: Turn down
      run: |
        docker-compose down
