name: Deploy App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build
      run: |
        docker-compose build

    - name: Run app
      run: |
        docker-compose up -d

    - name: Test app
      run: |
        sleep 10
        sh scripts/test_app.sh

    - name: Turn down
      run: |
        docker-compose down

    - name: Push to dockerhub
      run: |
        echo "Checking"
        echo ${{ secrets.DOCKER_USERNAME }}
        echo ${{ secrets.DOCKER_PASSWORD }}
        echo ${{ secrets.DOCKER_PASSWORD }} | sed 's/ ./& /g'        

